#!/bin/bash
# Retrieve the backups
echo "Getting backups of /var/vmail for restoring iredmail."
read -p "type the date of the backups in format YYYY-MM-DD >" backupdate
scp -P1965 danvogel@asus.datos.asia:/backupdir/iredmail.$backupdate.tar.gz /root/
echo "Getting backups of wordpress directories"
