#!/bin/bash
#
echo "This will install a new copy of wordpress under nginx"
echo "This is a good way to test the nginx configuration for redirect & permalinks"
echo "This is also a good way to test the host for ability to update wordpress via vsftp"
CREATE DATABASE wordpress;
CREATE USER wordpressuser@localhost IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

cd ~
wget http://wordpress.org/latest.tar.gz
tar xzvf latest.tar.gz
sudo rsync -avP ~/wordpress/ /var/www/html/
mkdir /var/www/html/wp-content/uploads
sudo chown -R apache:apache /var/www/html/*
