#!/bash/bin
# AWS Lightsail Launch Script to create LAMP server by adding mysql, php, and nginx
# mysql & http
# This will not install nginx because that will be installed along with the iredmail server
# in a following step.
#
echo "Begin LAMPWP setup script for MariaDB,PHP 7.3 and Wordpress">>/root/INSTALL.LOG
echo "Installing mariadb(mysql)" >>/root/INSTALL.LOG
yum install -y epel-release mariadb-server httpd mod_ssl
# remove test123 page
rm /etc/httpd/conf.d/welcome.conf 
systemctl start mariadb
systemctl enable mariadb
echo "there is no root password on mysql yet" >>/root/INSTALL.LOG
echo "mysql_secure_installation should be run manually or automated.">>/root/INSTALL.LOG
#
# php 7.3 install
yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum-config-manager --enable remi-php73
yum install -y php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-imap
php -v >>/root/INSTALL.LOG
#
#wordpress install
cd /root
echo "Downloading latest version of Wordpress into /root">>INSTALL.LOG
wget http://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz
mkdir /var/www/html/datostech.com
rsync -avP /root/wordpress/ /var/www/html/datostech.com
echo "Editing wp-config to add wordpress database name and user and password 'ChangeM3'">>INSTALL.LOG
cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
sed -i 's/database_name_here/wordpress/' /var/www/html/wp-config.php
sed -i 's/username_here/wpadmin/'  /var/www/html/wp-config.php
sed -i 's/password_here/ChangeM3/' /var/www/html/wp-config.php
#
# create database in mysql for new install of wp
echo "create database wordpress;">dbsetup.sql
echo "create user wpadmin@localhost identified by 'ChangeM3';">>dbsetup.sql
echo "grant all privileges on wordpress.* to wpadmin@localhost identified by 'ChangeM3';">>dbsetup.sql
echo "flush privileges;">>dbsetup.sql
echo "#mysql_secure_installation should be run manually or automated."
mysql -uroot <dbsetup.sql >>/root/INSTALL.LOG
#
cd /root/lightsail_wp/
# setup web server
#cp vhost.conf /etc/httpd/conf.d/
#start webserver
#systemctl enable httpd
#systemctl start httpd
#systemctl status httpd>>/root/INSTALL.LOG
#echo "vhost www.datos.asia added.  Please check with browser" >>/root/INSTALL.LOG
#echo "If mysql <dbsetup.sql failed, run now">>/root/INSTALL.LOG
#
# create user and copy keys for ssh login
useradd danvogel
mkdir -p /home/danvogel/.ssh
cp /home/centos/.ssh/authorized_keys /home/danvogel/.ssh/
chown -R danvogel:danvogel /home/danvogel/.ssh/*
hostnamectl set-hostname datos >>/root/INSTALL.LOG
echo "done.">>/root/INSTALL.LOG
yum update -y
reboot
