#!/bash/bin
# AWS Lightsail Launch Script to create LAMP server by adding mysql, php, and nginx
# mysql & http
# This will not install nginx because that will be installed along with the iredmail server
# in a following step.
#
echo "Begin LAMPWP setup script for MariaDB,PHP 7.3 and Wordpress">>/root/INSTALL.LOG
echo "Installing mariadb(mysql)" >>/root/INSTALL.LOG
yum install -y epel-release mariadb-server 
systemctl start mariadb
systemctl enable mariadb
echo "there is no root password on mysql yet" >>/root/INSTALL.LOG
echo "mysql_secure_installation should be run manually or automated.">>/root/INSTALL.LOG
#
# create database in mysql for new install of wp
echo "create database wordpress;">dbsetup.sql
echo "create user wpadmin@localhost identified by 'ChangeM3';">>dbsetup.sql
echo "grant all privileges on wordpress.* to wpadmin@localhost identified by 'ChangeM3';">>dbsetup.sql
echo "flush privileges;">>dbsetup.sql
echo "mysql_secure_installation should be run manually or automated."
mysql -uroot <dbsetup.sql >>/root/INSTALL.LOG
#
#
# php 7.3 install
yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum-config-manager --enable remi-php73
yum install libicu oniguruma5php
yum install -y php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-imap php-mbstring php73-php-int
yum install -y php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-imap php-mbstring php73-php-intl 
php -v >>/root/INSTALL.LOG
#
# create user and copy keys for ssh login
useradd danvogel
mkdir -p /home/danvogel/.ssh
cp /home/centos/.ssh/authorized_keys /home/danvogel/.ssh/
chown -R danvogel:danvogel /home/danvogel/.ssh/*
hostnamectl set-hostname datos >>/root/INSTALL.LOG
#
cp ssh-banner /etc/ssh/ssh-banner
echo "Banner /etc/ssh/ssh-banner" >> /etc/ssh/sshd_config
systemctl restart sshd
#
echo "done.">>/root/INSTALL.LOG
yum update -y
reboot
